### ISSUE TITLE
Dashboard is confusing

### ISSUE THREAD

**Issue by ceball** [pyviz-dev/status-dashboard#19]
Bit confused about what I'm looking at...

![Screenshot from 2019-12-22 16-15-49](https://user-images.githubusercontent.com/1929/71324412-596ae380-24d6-11ea-9946-e774844d2af0.png)

Lots of the badges don't seem to correspond to the column headings (I don't get what 'up' means under 'responsiveness', why the pypi badge has 'pyviz' in it, can you always assume website is from latest tag, and so on...).

**Comment by ceball** [comment]
Hmm, maybe some of the column headings are muddled? Though I'm not sure why I'd care when the last gh-pages commit was vs last commit to master. I probably don't get some of the intended meaning of various columns.

**Comment by ceball** [comment]
Guess I'll have a go at juggling them round and then someone can tell me what I've missed.

**Comment by philippjfr** [comment]
It's definitely missing a column header distinguishing between latest dev tag and latest released tag.
